k9s:
  cluster: cdevc01
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - mogenius
    - all
    - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
