#!/bin/sh
export BOUNDARY_ADDR="https://boundary.complero.info"
export BOUNDARY_AUTH_METHOD_ID="amoidc_LtAtiCyYbt"
[ $(command -v boundary) ] && complete -o nospace -C /opt/homebrew/bin/boundary boundary
