k9s:
  cluster: cc01
  namespace:
    active: default
    lockFavorites: false
    favorites:
    - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
