import = [
  #"/Users/jobstoit/.config/alacritty/catppuccin/catppuccin-macchiato.toml",
  "/Users/jobstoit/.config/alacritty/catppuccin/catppuccin-mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.90
blur = true
padding = { x = 0, y = 0 }
decorations = "Buttonless"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }

[colors.cursor]
cursor = '#ffffff'
