import = ["/Users/jobstoit/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
blur = true
padding = { x = 0, y = 0 }
decorations = "Buttonless"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }

[colors.cursor]
cursor = '#ffffff'
