k9s:
  cluster: boundary-complero
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - prod
    - dev
    - auxiliary
    - kube-system
  view:
    active: context
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
